<hr>

<footer>
	<p>&copy; <?=date('Y');?> Company, Inc.</p>
</footer>
</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
<script>
    var mainUrl = '<?=HOME;?>';
</script>
<script type="text/javascript" src=
"https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js">
</script>
<script type="text/javascript">
	<?php (new CodeExperts\Tools\Session())->sessionStart();?>
    const totalPurchase = '<?=isset($_SESSION['products_total']) ? $_SESSION['products_total'] : null;?>';;
    const sessionID = '<?=isset($_SESSION['session_pagseguro']) ? $_SESSION['session_pagseguro'] : null;?>';
    PagSeguroDirectPayment.setSessionId(sessionID);
</script>
<script src="<?=HOME;?>assets/js/drawPaymentMethodsDisplay.js"></script>
<script src="<?=HOME;?>assets/js/pagseguro.js"></script>
</body>
</html>
