<?php $msg = \CodeExperts\Tools\Session::getFlash('warning'); if($msg): ?>
	<div class="alert alert-warning">
		<?=$msg;?>
	</div>
<?php endif;?>

<?php $msg = \CodeExperts\Tools\Session::getFlash('error'); if($msg): ?>
    <div class="alert alert-danger">
        <?=$msg;?>
    </div>
<?php endif;?>

<?php $msg = \CodeExperts\Tools\Session::getFlash('success'); if($msg): ?>
    <div class="alert alert-success">
        <?=$msg;?>
    </div>
<?php endif;?>
