<?php require VIEWS_FOLDER . 'site/includes/header.phtml';?>
	<div class="jumbotron"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Escolha uma Forma de Pagamento</h1>
				<hr>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="msg"></div>
				<div class="payments">
					<h3>Carregando...</h3>
				</div>
			</div>
		</div>
<?php require VIEWS_FOLDER . 'site/includes/footer.phtml';?>