<?php require VIEWS_FOLDER . '/includes/header.phtml';?>
	<div class="row">
		<div class="col-md-12">
			<h1>Categoria</h1>
			<a href="<?=HOME . 'admin/category';?>" class="btn btn-warning">
				Voltar
			</a>
			<hr>
		</div>
	</div>
	<div class="row">
		<?php require VIEWS_FOLDER . '/includes/message.phtml'; ?>
	</div>
	<div class="row">
		<form action="<?=HOME . 'admin/category/edit';?>" method="POST">

		  <div class="form-group">
		    <label for="exampleInputEmail1">Nome</label>
		    <input type="text" class="form-control" placeholder="Nome" name="name" value="<?=$this->category['name'];?>">
		  </div>

		  <div class="form-group">
		    <label for="exampleInputEmail1">Descrição</label>
              <textarea class="form-control" name="description"><?=$this->category['description'];?></textarea>
		  </div>
		 	
		  <input type="hidden" name="id" value="<?=$this->category['id'];?>">
		  <button type="submit" class="btn btn-success">Salvar</button>
		</form>
	</div>
<?php require VIEWS_FOLDER . '/includes/footer.phtml';?>